id: P004402
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2DB4626
  title: མེས་པོའི་དགོངས་རྒྱན
  author: ''
  volumes:
    8e413ca0441242fab995d5d6cf2ee3ec:
      image_group_id: I1PD28094
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
